# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/ 
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 68f41c5354535de3624465f622093a01724bfecc

{
  "title": "табурет",
  "description": "складной"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/45/
Content-Type: application/json
Authorization: Token 68f41c5354535de3624465f622093a01724bfecc

{
  "title": "два шкафа"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-9-15
Content-Type: application/json

###

# удаление
DELETE {{baseUrl}}/advertisements/13/
Content-Type: application/json
Authorization: Token 68f41c5354535de3624465f622093a01724bfecc

###

