# Generated by Django 4.2.3 on 2023-08-28 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="sensor_id",
            new_name="sensor_id_id",
        ),
    ]
