# Generated by Django 4.2.3 on 2023-08-28 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0002_rename_sensor_id_measurement_sensor_id_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="sensor_id_id",
            new_name="sensor",
        ),
    ]
