# примеры API-запросов
 
@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика. Done
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик, джеймс датчик"
}

###

# обновление датчика. Done
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "В прихожей"
}

###

# добавление измерения. Done
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 26.3
}

###

# получение информации по датчику. Done
GET {{baseUrl}}/sensors/3/
Content-Type: application/json


###


  #получение подробной информации по датчику
  GET {{baseUrl}}/sensors/1/details/
  Content-Type: application/json

