# Generated by Django 4.2.3 on 2023-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="phones/photos/")),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField()),
                ("slug", models.SlugField(max_length=64, unique=True)),
            ],
        ),
    ]
